# Generated by Django 5.2.8 on 2025-11-10 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('category_type', models.CharField(choices=[('ROADSIDE', 'Roadside Assistance'), ('HEALTH', 'Health Assistance'), ('CARD_INSURANCE', 'Card Insurance')], max_length=20, unique=True, verbose_name='category type')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Icon name or class', max_length=50, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'service category',
                'verbose_name_plural': 'service categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('features', models.JSONField(default=list, help_text='List of features included', verbose_name='features')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monthly price')),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='yearly price')),
                ('max_requests_per_month', models.IntegerField(default=0, help_text='0 for unlimited', verbose_name='max requests per month')),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='coverage amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='services.servicecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'service plan',
                'verbose_name_plural': 'service plans',
                'ordering': ['category', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('last_renewal_date', models.DateField(blank=True, null=True, verbose_name='last renewal date')),
                ('next_renewal_date', models.DateField(blank=True, null=True, verbose_name='next renewal date')),
                ('requests_this_month', models.IntegerField(default=0, verbose_name='requests this month')),
                ('total_requests', models.IntegerField(default=0, verbose_name='total requests')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='services.serviceplan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'user service',
                'verbose_name_plural': 'user services',
                'ordering': ['-created_at'],
            },
        ),
    ]
