# Generated by Django 5.2.8 on 2025-11-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='auto renew'),
        ),
    ]
