# Generated by Django 5.2.8 on 2025-11-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_add_auto_renew_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days the subscription lasts (30 for monthly, 365 for yearly)', verbose_name='duration in days'),
        ),
    ]
