# Generated by Django 5.0.1 on 2025-12-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_production_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='category_type',
            field=models.CharField(choices=[('ROADSIDE', 'Roadside Assistance'), ('HEALTH', 'Health Assistance'), ('INSURANCE', 'Personal Accident Insurance'), ('CARD_INSURANCE', 'Card Insurance')], max_length=20, unique=True, verbose_name='category type'),
        ),
    ]
