# Generated by Django 5.0.1 on 2025-12-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicecategory_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='', verbose_name='terms and conditions'),
        ),
    ]
