# Generated by Django 5.2.8 on 2025-11-10 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('CHARGE', 'Charge'), ('CREDIT', 'Credit')], max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='currency')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='reference number')),
                ('external_transaction_id', models.CharField(blank=True, help_text='PAQ Wallet transaction ID', max_length=200, verbose_name='external transaction ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='status')),
                ('status_message', models.TextField(blank=True, verbose_name='status message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assistance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='assistance.assistancerequest', verbose_name='assistance request')),
            ],
            options={
                'verbose_name': 'wallet transaction',
                'verbose_name_plural': 'wallet transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
