# Generated by Django 5.2.8 on 2025-11-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paq_wallet', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='currency',
            field=models.CharField(default='GTQ', max_length=3, verbose_name='currency'),
        ),
    ]
