# Generated by Django 5.2.8 on 2025-11-22 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paq_wallet', '0003_alter_wallettransaction_currency'),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed at'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='user_service',
            field=models.ForeignKey(blank=True, help_text='Linked subscription payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='services.userservice', verbose_name='user service'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('UNKNOWN', 'Unknown')], default='PENDING', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='PAQ', max_length=50, verbose_name='provider')),
                ('event_type', models.CharField(max_length=50, verbose_name='event type')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('raw_payload', models.TextField(blank=True, verbose_name='raw payload')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('ERROR', 'Error'), ('LOGGED', 'Logged Only')], default='RECEIVED', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='received at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='paq_wallet.wallettransaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'payment webhook log',
                'verbose_name_plural': 'payment webhook logs',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'event_type'], name='paq_wallet__provide_afb9a1_idx'), models.Index(fields=['status', 'received_at'], name='paq_wallet__status_a39627_idx')],
            },
        ),
    ]
