# Generated by Django 5.2.8 on 2025-11-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paq_wallet', '0004_add_webhook_log_and_transaction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwebhooklog',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Unique identifier to prevent duplicate webhook processing', max_length=255, null=True, unique=True, verbose_name='idempotency key'),
        ),
        migrations.AlterField(
            model_name='paymentwebhooklog',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('ERROR', 'Error'), ('LOGGED', 'Logged Only'), ('DUPLICATE', 'Duplicate - Skipped')], default='RECEIVED', max_length=20, verbose_name='status'),
        ),
    ]
