"""
Django settings for segurifai_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from decimal import Decimal
from datetime import timedelta
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add apps directory to Python path
sys.path.insert(0, str(BASE_DIR / 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# CRITICAL: No default value - app will fail if SECRET_KEY not set in .env
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Changed default to False for security
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,.railway.app,paq.segurifai.shop', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',

    # Local apps
    'apps.core',  # Core utilities and security middleware
    'apps.users',
    'apps.services',
    'apps.providers',
    'apps.assistance',
    'apps.paq_wallet',
    'apps.gamification',
    'apps.promotions',
    'apps.bookings',
]

MIDDLEWARE = [
    # Django security first
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise must be early to serve static files before other middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # Security middleware (Cloudflare & OWASP)
    'apps.core.middleware.CloudflareSecurityMiddleware',
    'apps.core.middleware.RateLimitMiddleware',
    'apps.core.middleware.SecurityHeadersMiddleware',
    'apps.core.middleware.RequestValidationMiddleware',

    # Django core middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Audit logging - must be last to capture all request/response data
    'apps.core.middleware.AuditLoggingMiddleware',
]

ROOT_URLCONF = 'segurifai_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'segurifai_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
import dj_database_url
import os

# FORCE_SQLITE: Set to True in .env to use SQLite regardless of DATABASE_URL
# This is useful for local development when DATABASE_URL is set as a system variable
FORCE_SQLITE = config('FORCE_SQLITE', default=False, cast=bool)

# Check for DATABASE_URL (Railway/Heroku style) - but not if FORCE_SQLITE is True
DATABASE_URL = '' if FORCE_SQLITE else config('DATABASE_URL', default='')

if DATABASE_URL:
    # Normalize Supabase URL format (postgresql+psycopg:// -> postgresql://)
    if DATABASE_URL.startswith('postgresql+psycopg://'):
        DATABASE_URL = DATABASE_URL.replace('postgresql+psycopg://', 'postgresql://')

    # Use DATABASE_URL if provided (production - Railway/Supabase)
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # Fallback to individual variables (local development)
    DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')

    if DB_ENGINE == 'django.db.backends.sqlite3':
        # SQLite configuration for development
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / config('DB_NAME', default='db.sqlite3'),
            }
        }
    else:
        # PostgreSQL configuration
        DATABASES = {
            'default': {
                'ENGINE': DB_ENGINE,
                'NAME': config('DB_NAME', default='segurifai_db'),
                'USER': config('DB_USER', default='postgres'),
                'PASSWORD': config('DB_PASSWORD', default=''),
                'HOST': config('DB_HOST', default='localhost'),
                'PORT': config('DB_PORT', default='5432'),
            }
        }


# Password Hashers (Argon2 preferred for PCI-DSS compliance)
# https://docs.djangoproject.com/en/5.2/topics/auth/passwords/#using-argon2-with-django
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

# Password validation (Production-grade: minimum 12 characters per PCI-DSS/ISO 27001)
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # PCI-DSS/ISO 27001 recommendation
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise serves frontend assets from WHITENOISE_ROOT at the root URL
# This means /assets/main.js is served from frontend/dist/assets/main.js
WHITENOISE_ROOT = BASE_DIR / 'frontend' / 'dist'

# WhiteNoise storage for Django's static files (admin, etc.)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_TOKEN_LIFETIME', default=60, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=config('JWT_REFRESH_TOKEN_LIFETIME', default=1440, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Settings
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:5173,https://paq.segurifai.shop,https://web-production-14c11.up.railway.app',
    cast=Csv()
)
# Allow all Railway subdomains
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.railway\.app$",
    r"^https://.*\.up\.railway\.app$",
]
CORS_ALLOW_CREDENTIALS = True

# DRF Spectacular Settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'SegurifAI x PAQ API',
    'DESCRIPTION': 'API Documentation for SegurifAI Assistance Platform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# PAQ Wallet API Settings (PAQ-GO Integration for Guatemala)
# Token Generation & Query: https://www.paq.com.gt/paqpayws/emite.asmx
# Payment (PAQ-GO): https://www.paq.com.gt/paqgo/paqgo.asmx
PAQ_WALLET_EMITE_URL = config('PAQ_WALLET_EMITE_URL', default='https://www.paq.com.gt/paqpayws/emite.asmx')
PAQ_WALLET_PAQGO_URL = config('PAQ_WALLET_PAQGO_URL', default='https://www.paq.com.gt/paqgo/paqgo.asmx')
PAQ_WALLET_ID_CODE = config('PAQ_WALLET_ID_CODE', default='89E3AF')  # rep_id
PAQ_WALLET_USER = config('PAQ_WALLET_USER', default='APPW')  # usuario
PAQ_WALLET_PASSWORD = config('PAQ_WALLET_PASSWORD', default='123456')  # password

# PAQ SSO Authentication - CRITICAL: Must match PAQ app's secret
# All SegurifAI access is through PAQ app - no standalone registration
PAQ_SSO_SECRET = config('PAQ_SSO_SECRET', default='paq-segurifai-dev-secret-change-in-production')
PAQ_SSO_TOKEN_EXPIRY = config('PAQ_SSO_TOKEN_EXPIRY', default=300, cast=int)  # 5 minutes

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HTTPS Settings (enabled in production when DEBUG=False)
if not DEBUG:
    # Trust the X-Forwarded-Proto header from Railway's proxy
    # This prevents infinite redirect loops when behind a reverse proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CSRF Trusted Origins for production
CSRF_TRUSTED_ORIGINS = [
    'https://paq.segurifai.shop',
    'https://web-production-14c11.up.railway.app',
    'https://*.railway.app',
]

# Database Connection Settings
if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    DATABASES['default']['CONN_MAX_AGE'] = 600  # 10 minutes
    DATABASES['default']['OPTIONS'] = {'connect_timeout': 10}

# =============================================================================
# SECURITY MIDDLEWARE CONFIGURATION (Cloudflare & OWASP Compliance)
# =============================================================================

# Cloudflare Security Settings
CLOUDFLARE_ENABLED = config('CLOUDFLARE_ENABLED', default=False, cast=bool)
CLOUDFLARE_VERIFY_IP = config('CLOUDFLARE_VERIFY_IP', default=True, cast=bool)

# Allowed countries (ISO Alpha-2 codes) - Guatemala focus
ALLOWED_COUNTRIES = config(
    'ALLOWED_COUNTRIES',
    default='GT,US,MX,SV,HN,NI,CR,PA,BZ',  # Guatemala + Central America + US
    cast=Csv()
)

# Role-based rate limits (requests per minute)
# In DEBUG mode, use higher limits for testing
if DEBUG:
    RATE_LIMITS = {
        'ADMIN': 10000,
        'MAWDY_ADMIN': 10000,
        'PROVIDER': 10000,
        'USER': 10000,
        'ANONYMOUS': 10000,  # High limit for test suite
    }
else:
    RATE_LIMITS = {
        'ADMIN': 1000,
        'MAWDY_ADMIN': 500,
        'PROVIDER': 300,
        'USER': 200,
        'ANONYMOUS': 120,  # Increased for testing - can reduce later
    }

# Paths exempt from rate limiting (static files, health checks, etc.)
RATE_LIMIT_EXEMPT_PATHS = {
    '/',
    '/api/health/',
    '/api/docs/',
    '/api/schema/',
    '/api/redoc/',
    '/static/',
    '/assets/',
    '/favicon.ico',
    '/index.html',
}

# Security Headers Configuration
SECURITY_HEADERS = {
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'DENY',
    'X-XSS-Protection': '1; mode=block',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'geolocation=(self), microphone=()',
}

# Content Security Policy
CSP_POLICY = {
    'default-src': "'self'",
    'script-src': "'self' 'unsafe-inline' https://cdn.jsdelivr.net",
    'style-src': "'self' 'unsafe-inline' https://fonts.googleapis.com",
    'img-src': "'self' data: https:",
    'font-src': "'self' https://fonts.gstatic.com",
    'connect-src': "'self' https://api.paq.com.gt https://www.paq.com.gt",
    'frame-ancestors': "'none'",
}

# Audit Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            'format': '%(message)s',
        },
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 10,
            'formatter': 'json',
        },
        'audit_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'audit.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 30,
            'formatter': 'json',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'security': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'audit': {
            'handlers': ['console', 'audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Ensure logs directory exists (created at startup)
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# =============================================================================
# CENTRALIZED LOGGING (Production)
# =============================================================================
# Sentry for error tracking and performance monitoring
SENTRY_DSN = config('SENTRY_DSN', default='')
if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                transaction_style='url',
                middleware_spans=True,
            ),
            LoggingIntegration(
                level=None,  # Capture all as breadcrumbs
                event_level='ERROR',  # Send ERROR and above as events
            ),
        ],
        traces_sample_rate=0.1,  # 10% of transactions for performance
        send_default_pii=False,  # GDPR compliance
        environment=config('ENVIRONMENT', default='production'),
    )

# =============================================================================
# CLOUD STORAGE (AWS S3 for Media Files)
# =============================================================================
# In production, use S3 for media files instead of local storage
USE_S3_STORAGE = config('USE_S3_STORAGE', default=False, cast=bool)

if USE_S3_STORAGE:
    # AWS S3 Configuration
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

    # S3 Settings
    AWS_DEFAULT_ACL = 'private'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # 1 day cache
    }
    AWS_QUERYSTRING_AUTH = True  # Signed URLs for private files
    AWS_S3_FILE_OVERWRITE = False

    # Use S3 for media files
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

    # Optional: Use S3 for static files too
    # STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
    # STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'

# =============================================================================
# GOOGLE MAPS API (For Location Services)
# =============================================================================
# Required APIs in Google Cloud Console:
# 1. Maps JavaScript API - Frontend map display
# 2. Directions API - Route calculation & ETA
# 3. Distance Matrix API - Distance/time between multiple points
# 4. Geocoding API - Address <-> Coordinates conversion
# 5. Places API - Address autocomplete

GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='')
GOOGLE_MAPS_SERVER_KEY = config('GOOGLE_MAPS_SERVER_KEY', default='')  # For backend calls

# =============================================================================
# ANTHROPIC CLAUDE AI (For Vehicle/Health Validation)
# =============================================================================
# Claude AI API key for AI-powered validations
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='')

# =============================================================================
# PAQ WALLET TEST SETTINGS
# =============================================================================
# Test-user overrides (adjust via env; safe defaults keep legacy behaviour)
PAQ_TEST_PHONE = config('PAQ_TEST_PHONE', default='30082653')
PAQ_TEST_PRICE = config('PAQ_TEST_PRICE', default=Decimal('5.00'), cast=Decimal)
PAQ_TEST_MODE = config('PAQ_OTP_TEST_MODE', default=False, cast=bool)

# =============================================================================
# PAQ WEBHOOK SECURITY
# =============================================================================
# Webhook signature secret - REQUIRED in production (will fail without it)
PAQ_WEBHOOK_SECRET = config('PAQ_WEBHOOK_SECRET', default='')
