# Generated by Django 5.2.8 on 2025-11-21 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('icono', models.CharField(default='trophy', help_text='Nombre del icono (ej: trophy, star, medal)', max_length=50, verbose_name='icono')),
                ('puntos_bonus', models.PositiveIntegerField(default=25, verbose_name='puntos bonus')),
                ('condicion', models.CharField(help_text='Condicion para desbloquear (ej: modulos_completados >= 3)', max_length=100, verbose_name='condicion')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'logro',
                'verbose_name_plural': 'logros',
            },
        ),
        migrations.CreateModel(
            name='EducationalModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('categoria', models.CharField(choices=[('SEGURIDAD_VIAL', 'Seguridad Vial'), ('PRIMEROS_AUXILIOS', 'Primeros Auxilios'), ('FINANZAS_PERSONALES', 'Finanzas Personales'), ('PREVENCION', 'Prevencion')], max_length=30, verbose_name='categoria')),
                ('dificultad', models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='PRINCIPIANTE', max_length=20, verbose_name='dificultad')),
                ('contenido', models.TextField(help_text='Contenido educativo en formato markdown', verbose_name='contenido')),
                ('imagen_url', models.URLField(blank=True, verbose_name='imagen URL')),
                ('video_url', models.URLField(blank=True, verbose_name='video URL')),
                ('duracion_minutos', models.PositiveIntegerField(default=10, verbose_name='duracion en minutos')),
                ('puntos_completar', models.PositiveIntegerField(default=100, verbose_name='puntos al completar')),
                ('puntos_quiz_perfecto', models.PositiveIntegerField(default=50, help_text='Puntos extra por responder todas las preguntas correctamente', verbose_name='puntos quiz perfecto')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'modulo educativo',
                'verbose_name_plural': 'modulos educativos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(verbose_name='pregunta')),
                ('opcion_a', models.CharField(max_length=255, verbose_name='opcion A')),
                ('opcion_b', models.CharField(max_length=255, verbose_name='opcion B')),
                ('opcion_c', models.CharField(max_length=255, verbose_name='opcion C')),
                ('opcion_d', models.CharField(blank=True, max_length=255, verbose_name='opcion D')),
                ('respuesta_correcta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='respuesta correcta')),
                ('explicacion', models.TextField(blank=True, help_text='Explicacion de por que esta respuesta es correcta', verbose_name='explicacion')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='gamification.educationalmodule', verbose_name='modulo')),
            ],
            options={
                'verbose_name': 'pregunta de quiz',
                'verbose_name_plural': 'preguntas de quiz',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.PositiveIntegerField(default=0, verbose_name='puntos totales')),
                ('nivel', models.CharField(choices=[('NOVATO', 'Novato'), ('APRENDIZ', 'Aprendiz'), ('CONOCEDOR', 'Conocedor'), ('EXPERTO', 'Experto'), ('MAESTRO', 'Maestro')], default='NOVATO', max_length=20, verbose_name='nivel')),
                ('modulos_completados', models.PositiveIntegerField(default=0, verbose_name='modulos completados')),
                ('racha_dias', models.PositiveIntegerField(default=0, help_text='Dias consecutivos de actividad', verbose_name='racha de dias')),
                ('ultima_actividad', models.DateField(blank=True, null=True, verbose_name='ultima actividad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'puntos de usuario',
                'verbose_name_plural': 'puntos de usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtenido_en', models.DateTimeField(auto_now_add=True, verbose_name='obtenido en')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='gamification.achievement', verbose_name='logro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'logro de usuario',
                'verbose_name_plural': 'logros de usuarios',
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NO_INICIADO', 'No Iniciado'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado')], default='NO_INICIADO', max_length=20, verbose_name='estado')),
                ('quiz_completado', models.BooleanField(default=False, verbose_name='quiz completado')),
                ('respuestas_correctas', models.PositiveIntegerField(default=0, verbose_name='respuestas correctas')),
                ('total_preguntas', models.PositiveIntegerField(default=0, verbose_name='total preguntas')),
                ('puntos_obtenidos', models.PositiveIntegerField(default=0, verbose_name='puntos obtenidos')),
                ('iniciado_en', models.DateTimeField(blank=True, null=True, verbose_name='iniciado en')),
                ('completado_en', models.DateTimeField(blank=True, null=True, verbose_name='completado en')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='gamification.educationalmodule', verbose_name='modulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_educativo', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'progreso de usuario',
                'verbose_name_plural': 'progresos de usuarios',
                'unique_together': {('user', 'modulo')},
            },
        ),
    ]
