# Generated by Django 5.2.8 on 2025-11-22 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial_data'),
        ('promotions', '0001_initial_promo_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('POINT_THRESHOLD', 'Umbral de Puntos'), ('ACHIEVEMENT', 'Logro')], max_length=20, verbose_name='tipo de recompensa')),
                ('threshold', models.PositiveIntegerField(blank=True, null=True, verbose_name='umbral de puntos')),
                ('achievement_key', models.CharField(blank=True, max_length=50, verbose_name='clave de logro')),
                ('reward_data', models.JSONField(blank=True, default=dict, verbose_name='datos de recompensa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gamification_rewards', to='promotions.promocode', verbose_name='codigo promocional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_rewards', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'recompensa de usuario',
                'verbose_name_plural': 'recompensas de usuarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'reward_type'], name='gamificatio_user_id_80a653_idx'), models.Index(fields=['user', 'threshold'], name='gamificatio_user_id_1b1a1b_idx')],
            },
        ),
    ]
