# Generated by Django 5.2.8 on 2025-11-22 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_add_user_reward_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalmodule',
            name='credito_completar',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Creditos (GTQ) otorgados al completar el modulo', max_digits=5, verbose_name='credito al completar'),
        ),
        migrations.AddField(
            model_name='educationalmodule',
            name='credito_quiz_perfecto',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Creditos extra por quiz perfecto', max_digits=5, verbose_name='credito quiz perfecto'),
        ),
        migrations.CreateModel(
            name='UserDiscountCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, help_text='Creditos acumulados disponibles para usar', max_digits=10, verbose_name='saldo disponible')),
                ('total_acumulado', models.DecimalField(decimal_places=2, default=0, help_text='Total de creditos ganados historicamente', max_digits=10, verbose_name='total acumulado historico')),
                ('total_usado', models.DecimalField(decimal_places=2, default=0, help_text='Total de creditos usados en pagos', max_digits=10, verbose_name='total usado')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='ultimo uso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creditos_descuento', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'creditos de descuento',
                'verbose_name_plural': 'creditos de descuento',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GANADO', 'Credito Ganado'), ('USADO', 'Credito Usado'), ('EXPIRADO', 'Credito Expirado'), ('AJUSTE', 'Ajuste Manual')], max_length=20, verbose_name='tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripcion')),
                ('saldo_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='saldo despues')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_otorgados', to='gamification.educationalmodule', verbose_name='modulo')),
                ('user_credits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='gamification.userdiscountcredits', verbose_name='creditos de usuario')),
            ],
            options={
                'verbose_name': 'transaccion de credito',
                'verbose_name_plural': 'transacciones de credito',
                'ordering': ['-created_at'],
            },
        ),
    ]
