# Generated by Django 5.2.8 on 2025-11-22 01:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paq_wallet', '0004_add_webhook_log_and_transaction_fields'),
        ('services', '0003_add_auto_renew_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo unico para el descuento', max_length=50, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Porcentaje'), ('FIXED_AMOUNT', 'Monto Fijo'), ('FREE_TRIAL', 'Prueba Gratis')], default='PERCENTAGE', max_length=20, verbose_name='tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Porcentaje (0-100) o monto fijo en GTQ', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor del descuento')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Limite maximo de descuento para porcentajes', max_digits=10, null=True, verbose_name='descuento maximo')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Dejar vacio para usos ilimitados', null=True, verbose_name='usos maximos totales')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Cuantas veces puede usar este codigo cada usuario', verbose_name='usos maximos por usuario')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='usos actuales')),
                ('valid_from', models.DateTimeField(verbose_name='valido desde')),
                ('valid_until', models.DateTimeField(verbose_name='valido hasta')),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto minimo de compra requerido', max_digits=10, verbose_name='compra minima')),
                ('first_purchase_only', models.BooleanField(default=False, verbose_name='solo primera compra')),
                ('new_users_only', models.BooleanField(default=False, verbose_name='solo usuarios nuevos')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('EXPIRED', 'Expirado'), ('DEPLETED', 'Agotado')], default='ACTIVE', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='promo_codes', to='services.servicecategory', verbose_name='categorias aplicables')),
                ('applicable_plans', models.ManyToManyField(blank=True, help_text='Dejar vacio para aplicar a todos los planes', related_name='promo_codes', to='services.serviceplan', verbose_name='planes aplicables')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'codigo promocional',
                'verbose_name_plural': 'codigos promocionales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('start_date', models.DateTimeField(verbose_name='fecha inicio')),
                ('end_date', models.DateTimeField(verbose_name='fecha fin')),
                ('target_audience', models.CharField(blank=True, help_text='Descripcion del publico objetivo', max_length=100, verbose_name='audiencia objetivo')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='presupuesto')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activa'), ('PAUSED', 'Pausada'), ('COMPLETED', 'Completada')], default='DRAFT', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('promo_codes', models.ManyToManyField(related_name='campaigns', to='promotions.promocode', verbose_name='codigos promocionales')),
            ],
            options={
                'verbose_name': 'campana',
                'verbose_name_plural': 'campanas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio original')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto descontado')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio final')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='usado en')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.promocode', verbose_name='codigo promocional')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code_usages', to='paq_wallet.wallettransaction', verbose_name='transaccion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('user_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code_usages', to='services.userservice', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'uso de codigo promocional',
                'verbose_name_plural': 'usos de codigos promocionales',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='promotions__code_2587f5_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['status', 'valid_from', 'valid_until'], name='promotions__status_aa7faa_idx'),
        ),
    ]
