# Generated by Django 5.2.8 on 2025-11-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_production_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'SegurifAI Super Admin'), ('SEGURIFAI_TEAM', 'SegurifAI Team Member'), ('USER', 'User'), ('PROVIDER', 'Assistance Provider'), ('MAWDY_ADMIN', 'MAWDY Administrator'), ('MAWDY_FIELD_TECH', 'MAWDY Field Technician'), ('PAQ_ADMIN', 'PAQ Administrator')], default='USER', max_length=20, verbose_name='role'),
        ),
    ]
