# Generated by Django 5.0.1 on 2025-12-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_of_birth_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='home latitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='home longitude'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='Guatemala', max_length=100, verbose_name='country'),
        ),
    ]
