# Generated by Django 5.2.8 on 2025-11-10 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='company name')),
                ('business_license', models.CharField(max_length=100, unique=True, verbose_name='business license')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='tax ID')),
                ('business_phone', models.CharField(max_length=20, verbose_name='business phone')),
                ('business_email', models.EmailField(max_length=254, verbose_name='business email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('country', models.CharField(default='Mexico', max_length=100, verbose_name='country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('service_radius_km', models.IntegerField(default=50, verbose_name='service radius (km)')),
                ('service_areas', models.JSONField(default=list, help_text='List of cities/areas served', verbose_name='service areas')),
                ('is_available', models.BooleanField(default=True, verbose_name='currently available')),
                ('working_hours', models.JSONField(default=dict, help_text='Working hours by day: {"monday": {"start": "08:00", "end": "18:00"}, ...}', verbose_name='working hours')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='average rating')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='total reviews')),
                ('total_completed', models.IntegerField(default=0, verbose_name='total completed requests')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='providers/certificates/', verbose_name='certificate')),
                ('insurance_policy', models.FileField(blank=True, null=True, upload_to='providers/insurance/', verbose_name='insurance policy')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20, verbose_name='status')),
                ('verification_notes', models.TextField(blank=True, verbose_name='verification notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'provider review',
                'verbose_name_plural': 'provider reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
