# Generated by Django 5.2.8 on 2025-11-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='service_categories',
            field=models.ManyToManyField(related_name='providers', to='services.servicecategory', verbose_name='service categories'),
        ),
    ]
