# Generated by Django 5.2.8 on 2025-11-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='country',
            field=models.CharField(default='Guatemala', max_length=100, verbose_name='country'),
        ),
    ]
