# Generated by Django 5.2.8 on 2025-11-22 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0005_add_assistance_document_ai_review'),
        ('providers', '0004_alter_provider_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('heading', models.FloatField(blank=True, help_text='Direction of movement in degrees (0-360)', null=True, verbose_name='heading (degrees)')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='speed (km/h)')),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True, verbose_name='accuracy (meters)')),
                ('is_online', models.BooleanField(default=True, verbose_name='is online')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='providers.provider', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'provider location',
                'verbose_name_plural': 'provider locations',
            },
        ),
        migrations.CreateModel(
            name='ProviderLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('heading', models.FloatField(blank=True, null=True, verbose_name='heading')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='speed')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('assistance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_locations', to='assistance.assistancerequest', verbose_name='assistance request')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='providers.provider', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'provider location history',
                'verbose_name_plural': 'provider location history',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['provider', 'recorded_at'], name='providers_p_provide_030f21_idx'), models.Index(fields=['assistance_request', 'recorded_at'], name='providers_p_assista_c8d3b0_idx')],
            },
        ),
    ]
