# Generated by Django 5.2.8 on 2025-11-23 02:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0005_add_assistance_document_ai_review'),
        ('providers', '0005_add_provider_location_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTechProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Motocicleta'), ('CAR', 'Automovil'), ('TOW_TRUCK', 'Grua'), ('AMBULANCE', 'Ambulancia')], default='MOTORCYCLE', max_length=20)),
                ('vehicle_plate', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('service_capabilities', models.JSONField(default=list, help_text='List of service codes tech can handle: ["CERRAJERIA", "COMBUSTIBLE", ...]')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente Aprobacion'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('INACTIVE', 'Inactivo')], default='PENDING', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=3)),
                ('total_jobs_completed', models.IntegerField(default=0)),
                ('total_jobs_accepted', models.IntegerField(default=0)),
                ('total_jobs_declined', models.IntegerField(default=0)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('weekly_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('daily_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fcm_token', models.CharField(blank=True, help_text='Firebase Cloud Messaging token', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_tech_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Tech Profile',
                'verbose_name_plural': 'Field Tech Profiles',
            },
        ),
        migrations.CreateModel(
            name='FieldTechShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='providers.fieldtechprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldTechLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='providers.fieldtechprofile')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='providers.fieldtechshift')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['tech', 'recorded_at'], name='providers_f_tech_id_4ac9c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('DECLINED', 'Rechazado'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_arrival_minutes', models.IntegerField()),
                ('base_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('assistance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='assistance.assistancerequest')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='providers.fieldtechprofile')),
            ],
            options={
                'ordering': ['priority', 'offered_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='providers_j_status_1e3be0_idx'), models.Index(fields=['tech', 'status'], name='providers_j_tech_id_6f71f3_idx')],
            },
        ),
    ]
