# Generated by Django 5.2.8 on 2025-11-24 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0006_evidence_form'),
        ('providers', '0006_dispatch_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('JOB_CREATED', 'Trabajo Creado'), ('JOB_OFFERED', 'Oferta Enviada'), ('JOB_ACCEPTED', 'Oferta Aceptada'), ('JOB_DECLINED', 'Oferta Rechazada'), ('JOB_EXPIRED', 'Oferta Expirada'), ('JOB_CANCELLED', 'Trabajo Cancelado'), ('JOB_COMPLETED', 'Trabajo Completado'), ('TECH_ONLINE', 'Técnico En Línea'), ('TECH_OFFLINE', 'Técnico Desconectado'), ('TECH_LOCATION', 'Ubicación Actualizada'), ('DISPATCH_STARTED', 'Despacho Iniciado'), ('TECH_EN_ROUTE', 'Técnico En Camino'), ('TECH_ARRIVED', 'Técnico Llegó'), ('SERVICE_STARTED', 'Servicio Iniciado'), ('SERVICE_COMPLETED', 'Servicio Completado'), ('ADMIN_REASSIGN', 'Reasignación por Admin'), ('ADMIN_CANCEL', 'Cancelación por Admin')], max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='assistance.assistancerequest')),
                ('job_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='providers.joboffer')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_actions', to=settings.AUTH_USER_MODEL)),
                ('tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='providers.fieldtechprofile')),
            ],
            options={
                'verbose_name': 'Dispatch Action Log',
                'verbose_name_plural': 'Dispatch Action Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='providers_d_action_0560ee_idx'), models.Index(fields=['assistance_request', 'created_at'], name='providers_d_assista_ed38c5_idx'), models.Index(fields=['tech', 'created_at'], name='providers_d_tech_id_508b14_idx')],
            },
        ),
    ]
