# Generated by Django 5.2.8 on 2025-11-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_add_dispatch_action_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='completion_data',
            field=models.JSONField(blank=True, help_text='Completion form data: notes, photos, signature, customer satisfaction', null=True),
        ),
    ]
