# Generated by Django 5.2.8 on 2025-11-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='request number')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20, verbose_name='priority')),
                ('location_address', models.TextField(verbose_name='location address')),
                ('location_city', models.CharField(max_length=100, verbose_name='city')),
                ('location_state', models.CharField(max_length=100, verbose_name='state')),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('vehicle_make', models.CharField(blank=True, max_length=100, verbose_name='vehicle make')),
                ('vehicle_model', models.CharField(blank=True, max_length=100, verbose_name='vehicle model')),
                ('vehicle_year', models.IntegerField(blank=True, null=True, verbose_name='vehicle year')),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, verbose_name='vehicle plate')),
                ('patient_name', models.CharField(blank=True, max_length=200, verbose_name='patient name')),
                ('patient_age', models.IntegerField(blank=True, null=True, verbose_name='patient age')),
                ('symptoms', models.TextField(blank=True, verbose_name='symptoms')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='card last 4 digits')),
                ('incident_type', models.CharField(blank=True, help_text='Fraud, theft, etc.', max_length=100, verbose_name='incident type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned to Provider'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='estimated arrival time')),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='actual arrival time')),
                ('completion_time', models.DateTimeField(blank=True, null=True, verbose_name='completion time')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='estimated cost')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='actual cost')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'assistance request',
                'verbose_name_plural': 'assistance requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PHOTO', 'Photo'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('REPORT', 'Report'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='document type')),
                ('file', models.FileField(upload_to='assistance/documents/', verbose_name='file')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'request document',
                'verbose_name_plural': 'request documents',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('MESSAGE', 'Message'), ('LOCATION_UPDATE', 'Location Update'), ('ARRIVAL_UPDATE', 'Arrival Update')], default='MESSAGE', max_length=20, verbose_name='update type')),
                ('message', models.TextField(verbose_name='message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'request update',
                'verbose_name_plural': 'request updates',
                'ordering': ['created_at'],
            },
        ),
    ]
