# Generated by Django 5.2.8 on 2025-11-10 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistance', '0003_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='user_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='services.userservice', verbose_name='user service'),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assistance.assistancerequest', verbose_name='request'),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
        migrations.AddField(
            model_name='requestupdate',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='assistance.assistancerequest', verbose_name='request'),
        ),
        migrations.AddField(
            model_name='requestupdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_updates', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['status', 'created_at'], name='assistance__status_b20537_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['user', 'status'], name='assistance__user_id_fb0416_idx'),
        ),
        migrations.AddIndex(
            model_name='assistancerequest',
            index=models.Index(fields=['provider', 'status'], name='assistance__provide_29db3d_idx'),
        ),
    ]
