# Generated by Django 5.2.8 on 2025-11-22 01:24

import apps.assistance.documents
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PHOTO_VEHICLE', 'Foto del Vehiculo'), ('PHOTO_DAMAGE', 'Foto del Dano'), ('PHOTO_LOCATION', 'Foto de Ubicacion'), ('LICENSE_PLATE', 'Placa del Vehiculo'), ('DRIVER_LICENSE', 'Licencia de Conducir'), ('INSURANCE_CARD', 'Tarjeta de Seguro'), ('MEDICAL_PRESCRIPTION', 'Receta Medica'), ('MEDICAL_REPORT', 'Informe Medico'), ('CREDIT_CARD_STATEMENT', 'Estado de Cuenta'), ('POLICE_REPORT', 'Reporte Policial'), ('OTHER', 'Otro')], max_length=30, verbose_name='tipo de documento')),
                ('file', models.FileField(upload_to=apps.assistance.documents.AssistanceDocument.document_upload_path, verbose_name='archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nombre original')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='tamano en bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='tipo MIME')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pendiente de Revision'), ('REVIEWING', 'En Revision'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('NEEDS_RESUBMIT', 'Requiere Reenvio')], default='PENDING', max_length=20, verbose_name='estado de revision')),
                ('ai_confidence_score', models.FloatField(blank=True, help_text='0.0 - 1.0', null=True, verbose_name='puntuacion de confianza IA')),
                ('ai_review_notes', models.TextField(blank=True, verbose_name='notas de revision IA')),
                ('ai_detected_issues', models.JSONField(blank=True, default=list, verbose_name='problemas detectados')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisado en')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='subido en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_documents', to='assistance.assistancerequest', verbose_name='solicitud')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
            ],
            options={
                'verbose_name': 'documento de asistencia',
                'verbose_name_plural': 'documentos de asistencia',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
