# Generated by Django 5.2.8 on 2025-11-23 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0005_add_assistance_document_ai_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('VEHICLE_DAMAGE', 'Dano al Vehiculo'), ('ROADSIDE_ISSUE', 'Problema en Carretera'), ('HEALTH_INCIDENT', 'Incidente de Salud'), ('GENERAL', 'Formulario General')], default='GENERAL', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviado'), ('REVIEWING', 'En Revision'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('NEEDS_INFO', 'Requiere Mas Informacion')], default='DRAFT', max_length=20)),
                ('incident_date', models.DateTimeField(verbose_name='fecha del incidente')),
                ('incident_description', models.TextField(verbose_name='descripcion del incidente')),
                ('location_description', models.TextField(verbose_name='descripcion de la ubicacion')),
                ('vehicle_make', models.CharField(blank=True, max_length=100, verbose_name='marca del vehiculo')),
                ('vehicle_model', models.CharField(blank=True, max_length=100, verbose_name='modelo del vehiculo')),
                ('vehicle_year', models.IntegerField(blank=True, null=True, verbose_name='ano del vehiculo')),
                ('vehicle_color', models.CharField(blank=True, max_length=50, verbose_name='color del vehiculo')),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, verbose_name='placa del vehiculo')),
                ('damage_description', models.TextField(blank=True, verbose_name='descripcion del dano')),
                ('damage_location', models.CharField(blank=True, help_text='ej: frente, trasero, lado izquierdo', max_length=100, verbose_name='ubicacion del dano')),
                ('symptoms_description', models.TextField(blank=True, verbose_name='descripcion de sintomas')),
                ('medical_history', models.TextField(blank=True, verbose_name='historial medico relevante')),
                ('current_medications', models.TextField(blank=True, verbose_name='medicamentos actuales')),
                ('allergies', models.TextField(blank=True, verbose_name='alergias conocidas')),
                ('issue_type', models.CharField(blank=True, help_text='ej: llanta ponchada, sin combustible, bateria', max_length=100, verbose_name='tipo de problema')),
                ('attempted_solutions', models.TextField(blank=True, verbose_name='soluciones intentadas')),
                ('witness_name', models.CharField(blank=True, max_length=200, verbose_name='nombre del testigo')),
                ('witness_phone', models.CharField(blank=True, max_length=20, verbose_name='telefono del testigo')),
                ('declaration_accepted', models.BooleanField(default=False, help_text='Declaro que la informacion proporcionada es veridica', verbose_name='declaracion aceptada')),
                ('declaration_timestamp', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, verbose_name='notas de revision')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='razon de rechazo')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, verbose_name='analisis de IA')),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_forms', to='assistance.assistancerequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidence_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formulario de evidencia',
                'verbose_name_plural': 'formularios de evidencia',
                'ordering': ['-created_at'],
            },
        ),
    ]
