# Generated by Django 5.2.8 on 2025-11-24 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0006_evidence_form'),
        ('services', '0004_production_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='service_category',
            field=models.ForeignKey(blank=True, help_text='Optional for MAWDY direct requests', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='services.servicecategory', verbose_name='service category'),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='user_service',
            field=models.ForeignKey(blank=True, help_text='Optional for MAWDY direct requests', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='services.userservice', verbose_name='user service'),
        ),
    ]
