# Generated by Django 5.2.8 on 2025-11-25 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0007_make_service_fields_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='assigned at'),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='assigned_tech',
            field=models.ForeignKey(blank=True, help_text='Direct technician assignment (MAWDY field tech)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests_as_tech', to=settings.AUTH_USER_MODEL, verbose_name='assigned technician'),
        ),
    ]
