# Generated by Django 5.0.1 on 2025-11-25 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0008_assistancerequest_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('patient_age', models.CharField(max_length=10)),
                ('patient_gender', models.CharField(max_length=20)),
                ('consciousness_level', models.CharField(max_length=20)),
                ('breathing_difficulty', models.BooleanField(default=False)),
                ('chest_pain', models.BooleanField(default=False)),
                ('bleeding', models.BooleanField(default=False)),
                ('pre_existing_conditions', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('people_affected', models.CharField(default='1', max_length=10)),
                ('validation_status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING_REVIEW', 'Pending Manual Review'), ('REJECTED', 'Rejected'), ('FAILED', 'Validation Failed')], default='PENDING_REVIEW', max_length=20)),
                ('urgency_level', models.CharField(choices=[('CRITICAL', 'Critical - Immediate Response'), ('HIGH', 'High - Urgent'), ('MEDIUM', 'Medium - Soon'), ('LOW', 'Low - Routine')], default='MEDIUM', max_length=20)),
                ('validation_message', models.TextField(blank=True)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_health_validations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'validation_status'], name='assistance__user_id_f7ce5d_idx'), models.Index(fields=['urgency_level'], name='assistance__urgency_5d1c05_idx'), models.Index(fields=['created_at'], name='assistance__created_7388dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('plate', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('validation_status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING_REVIEW', 'Pending Manual Review'), ('REJECTED', 'Rejected'), ('FAILED', 'Validation Failed')], default='PENDING_REVIEW', max_length=20)),
                ('validation_message', models.TextField(blank=True)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_validations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'validation_status'], name='assistance__user_id_f5f855_idx'), models.Index(fields=['plate'], name='assistance__plate_b6d32e_idx')],
            },
        ),
    ]
