# Generated by Django 5.0.1 on 2025-12-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0009_healthvalidation_vehiclevalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='card_claim_info',
            field=models.JSONField(blank=True, default=dict, help_text='Card fraud claim details', verbose_name='card claim info'),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='health_info',
            field=models.JSONField(blank=True, default=dict, help_text='SAMPLE questionnaire data', verbose_name='health info'),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='contact phone'),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='service_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='SegurifAI service info', verbose_name='service metadata'),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='vehicle_info',
            field=models.JSONField(blank=True, default=dict, help_text='Full vehicle details', verbose_name='vehicle info'),
        ),
    ]
