# Generated by Django 5.0.1 on 2025-12-03 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='codigo de referencia')),
                ('service_type', models.CharField(choices=[('ROADSIDE', 'Asistencia Vial'), ('HEALTH', 'Asistencia Medica'), ('CONSULTATION', 'Consulta'), ('TOWING', 'Grua'), ('FUEL', 'Combustible'), ('TIRE', 'Cambio de Neumatico'), ('BATTERY', 'Paso de Corriente'), ('LOCKSMITH', 'Cerrajeria'), ('AMBULANCE', 'Ambulancia'), ('MEDICAL_APPOINTMENT', 'Cita Medica'), ('LAB_EXAM', 'Examen de Laboratorio'), ('PSYCHOLOGY', 'Psicologia'), ('NUTRITION', 'Nutricion'), ('OTHER', 'Otro')], default='OTHER', max_length=30, verbose_name='tipo de servicio')),
                ('service_name', models.CharField(max_length=200, verbose_name='nombre del servicio')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado'), ('NO_SHOW', 'No Asistio'), ('RESCHEDULED', 'Reprogramado')], default='PENDING', max_length=20, verbose_name='estado')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10, verbose_name='prioridad')),
                ('scheduled_date', models.DateField(verbose_name='fecha programada')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='hora programada')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60, verbose_name='duracion estimada (minutos)')),
                ('location_address', models.CharField(blank=True, max_length=500, verbose_name='direccion')),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitud')),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitud')),
                ('location_notes', models.TextField(blank=True, help_text='Instrucciones adicionales para llegar', verbose_name='notas de ubicacion')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='nombre de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='telefono de contacto')),
                ('user_notes', models.TextField(blank=True, verbose_name='notas del usuario')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas visibles solo para administradores', verbose_name='notas internas')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado en')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='razon de cancelacion')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completado en')),
                ('completion_notes', models.TextField(blank=True, verbose_name='notas de finalizacion')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Calificacion del 1 al 5', null=True, verbose_name='calificacion')),
                ('rating_comment', models.TextField(blank=True, verbose_name='comentario de calificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('assigned_provider', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['PROVIDER', 'MAWDY_FIELD_TECH']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL, verbose_name='proveedor asignado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-scheduled_date', '-scheduled_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado'), ('NO_SHOW', 'No Asistio'), ('RESCHEDULED', 'Reprogramado')], max_length=20, verbose_name='estado anterior')),
                ('new_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado'), ('NO_SHOW', 'No Asistio'), ('RESCHEDULED', 'Reprogramado')], max_length=20, verbose_name='nuevo estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking', verbose_name='reserva')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='cambiado por')),
            ],
            options={
                'verbose_name': 'historial de estado',
                'verbose_name_plural': 'historial de estados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reference_code'], name='bookings_bo_referen_543fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_date', 'status'], name='bookings_bo_schedul_75f830_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'priority'], name='bookings_bo_status_99a58f_idx'),
        ),
    ]
